maquina/expendedora/urls.py
from django.urls import path
from . import views

app_name = "expendedora"

urlpatterns = [
    path('', views.index, name='index'),
    path('enviar/', views.enviar, name='enviar'),
    
]

maquina/maquina/urls.py
from django.urls import path, include

urlpatterns = [
    path('maquina/', include('expendedora.urls'))
]

maquina/expendedora/models.py
from django.db import models

# Create your models here.

class Productos(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=5, decimal_places=2)

maquina/expendedora/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
from .models import Productos

def index(request):
    productos = Productos.objects.order_by('id')
    context = {'productos':productos}
    return render(request, 'index.html', context)

def enviar(request):
    saldo = request.POST['saldo']
    codigo = request.POST['codigo']
    try:
        producto = opc(codigo)
        context = saldo_rest(saldo, producto.precio)

        return HttpResponse(context)

    except AttributeError:
        return redirect('expendedora:index')
    except ValueError:
        return redirect('expendedora:index')

def saldo_rest(saldo, costo):
    saldo = float(saldo)
    costo = float(costo)
    
    if saldo < costo:
        msj = 'No tiene el monto para el producto seleccionado'
        return msj
    else:
        restante = saldo-costo
        msj = 'El saldo restante es: ' + str(restante) + ' Gracias por la compra !!!'
        return msj

def opc(opc):
    opc = int(opc)

    try:
        if opc>=1 and opc<=10:
            producto = Productos.objects.get(id=opc)
            return producto
    except ValueError:
        return redirect('expendedora:index')
    else:
        return redirect('expendedora:index')

maquina/expendedora/templates/base.html
<!doctype html>
    <html lang="es">
        <head>
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

            <title>
                {% block title %}
                {% endblock title %}
            </title>
        </head>
    <body>
        {% block body %}
        {% endblock body %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    </body>
</html>

maquina/expendedora/templates/index.html
{% extends "base.html" %}

{% block title %}
    Máquina Expendedora
{% endblock title %}

{% block body %}
    <div class="container text-center bg-light">
        <div class="row">
            <div class="col-12">
                <h1 class="my-2">La Máquina Expendedora</h1>
            </div>
            <div class="col-3">
                <h2>Lista de productos</h2>
                <table class="table my-4">
                    <thead>
                        <tr>
                            <th scope="col h3">Código</th>
                            <th scope="col h3">Producto</th>
                            <th scope="col h3">Precio</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for producto in productos %}
                        <tr>
                            <th scope="row">{{ producto.id }}</th>
                            <td>{{ producto.nombre }}</td>
                            <td>{{ producto.precio }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-6">
                <h2>Ingreso</h2>
                <form method="POST" action="{% url 'expendedora:enviar' %}">
                    <div class="row">
                        {% csrf_token %}
                        <div class="col form-group">
                            <label for="prod">Código de producto</label>
                            <input type="text" class="form-control" id="prod" name="codigo">
                        </div>
                        <div class="col form-group">
                            <label for="sald">Saldo</label>
                            <input type="text" class="form-control" id="sald" name="saldo" placeholder="999.50">
                        </div>
                    </div>
                    <input class="btn btn-outline-primary" type="submit" value="Enviar">
                </form>
            </div>
            <div class="col-3">
                <h2>Salida</h2>

            </div>
        </div>
    </div>

{% endblock body %}